DataHub/home/urls.py
from django.urls import path
#from user import views as user_view 

from . import views

app_name = 'home'
urlpatterns = [
    #path('', views.index, name = 'mainpage'),
    path('', views.ProfileListView.as_view(), name = 'all-profiles-view'),
    path('signup/', views.signup_view, name = 'signup'),
    path('login/', views.login_view, name = 'login'),
    path('logout/', views.logout_view, name = 'user_logout'),
    path('myprofile/', views.my_profile_view, name = 'my-profile'),
    path('<slug>/', views.ProfileDetailView.as_view(), name='profile-detail-view'),
]

DataHub/home/models.py
from django.db import models
from django.contrib.auth.models import User
from .utils import get_random_code
from django.template.defaultfilters import slugify
from django.shortcuts import reverse
from django.db.models import Q


class ProfileManager(models.Manager):
    
    def get_all_profiles(self):
        profiles = Profile.objects.all()
        return profiles

class Profile(models.Model):
    first_name = models.CharField(max_length=200, blank=False)
    last_name = models.CharField(max_length=200, blank=False)
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    description = models.TextField(max_length=500, blank=False)
    email = models.EmailField(max_length=200, blank=False)
    country = models.EmailField(max_length=200, blank=True)
    avatar = models.ImageField(default='avatar.webp', upload_to='images/')
    slug = models.SlugField(unique=True, blank=True)
    link = models.TextField(blank=False)

    objects = ProfileManager()
    #followers = models.ManyToManyField(User, blank=True, related_name='followers')
    #liked = models.ManyToManyField(User, blank=True, related_name='likes')

    # install pillow
    #create media_root
    # find avatr.png

    # def __str__(self):
    #     return f"{self.user.username}-{self.created}"
    # def num_likes(self):
    #     return self.liked.all().count()

    # def get_followers(self):
    #     return self.followers.all()

    # def get_followers_no(self):
    #     return self.followers.all().count()

    def get_absolute_url(self):
        return reverse("home:profile-detail-view", kwargs={"slug": self.slug})

    __initial_first_name = None
    __initial_last_name = None

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__initial_first_name = self.first_name
        self.__initial_last_name = self.last_name

    def save(self, *args, **kwargs):
        ex = False
        to_slug = self.slug
        if self.first_name != self.__initial_first_name or self.last_name != self.__initial_last_name or self.slug=="":
            if self.first_name and self.last_name:
                to_slug = slugify(str(self.first_name) + " " + str(self.last_name))
                ex = Profile.objects.filter(slug=to_slug).exists()
                while ex:
                    to_slug = slugify(to_slug + " " + str(get_random_code()))
                    ex = Profile.objects.filter(slug=to_slug).exists()
            else:
                to_slug = str(self.user)
        self.slug = to_slug
        super().save(*args, **kwargs)

DataHub/home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password', 'email')

class UserProfileInfoForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['avatar'].label = "Profile Picture"
        self.fields['description'].label = "Bio"

    class Meta():
         model = Profile
         fields = ('avatar', 'description')
         widgets = {
          'description': forms.Textarea(attrs={'rows':1, 'cols':50}),
         }

DataHub/home/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.contrib import messages 
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Profile, ProfileManager
from django.views.generic import ListView, DetailView
from django.db.models import Q
from django.core.exceptions import *
from .forms import UserForm, UserProfileInfoForm
from django.urls import reverse
# from django.shortcuts import render, redirect, get_object_or_404



# def index(request): 
#     return render(request, "home/mainpage.html", {})

def signup_view(request):
    registered = False
    if request.method=='POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'avatar' in request.FILES:
                profile.avatar=request.FILES['avatar']
            profile.save()

            registered = True

            return HttpResponseRedirect('/login')
        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'home/signup.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})


def login_view(request):
    # valuenext= request.POST.get()
    # print(valuenext )
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                if 'next' in request.POST:
                    return HttpResponseRedirect(request.POST.get('next'))
                return HttpResponseRedirect('/')
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:

        return render(request, 'home/login.html', {})



# Create your views here.
@login_required
def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/')

@login_required
def my_profile_view(request):
    profile = Profile.objects.get(user=request.user)
    user = request.user
    context = {
        'profile': profile,
    }

    return render(request, 'home/myprofile.html', context)

# def like_unlike(request):
#     if request.method == 'POST':
#         account_id = request.POST.get('account_id')
#         profile_obj = Profile.objects.get(id=account_id)
#         profile_obj.liked.add("Like")

def profiles_list(request):
    profiles =Profile.objects.get_all_profiles()
    context = {
        'profiles': profiles,
    }

    return render(request, 'home/profiles_list.html', context)

class ProfileDetailView(LoginRequiredMixin, DetailView):
    model= Profile
    template_name = 'home/detail.html'

    # def get_object(self, slug=None):
    #     slug = self.kwargs.get('slug')
    #     profile = Profile.objects.get(slug=slug)
    #     return profile
    #     try: 
    #         profile = Profile.objects.get(slug=slug)
    #         return profile
    #     except:
    #         print('Data Not Found')
    #     finally: 
    #         return profile
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) 
        try:
            user = User.objects.get(username__iexact=self.request.user) 
            profile = Profile.objects.get(user=user)
        except ObjectDoesNotExist:
            print('Data Not Found')
       
        return context

class ProfileListView(ListView):
    model = Profile
    template_name = 'home/mainpage.html'
    #context_object_name = 'profiles'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) 
        try: 
            user = User.objects.get(username__iexact=self.request.user)
            profile = Profile.objects.get(user=user)
        except ObjectDoesNotExist:
            print('Data Not Found')
        
        return context

DataHub/home/templates/home/detail.html
{% load static %}
<!doctype html>

<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
 <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
 <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
 <!------ Include the above in your HEAD tag ---------->
 
 <head>
     <link rel="stylesheet" type="text/css" href="{% static 'home/mainpage.css' %}">
     <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons">
     <link rel="stylesheet" href="https://unpkg.com/bootstrap-material-design@4.1.1/dist/css/bootstrap-material-design.min.css" integrity="sha384-wXznGJNEXNG1NFsbm0ugrLFMQPWswR3lds2VeinahP8N0zJw9VWSopbjv2x7WCvX" crossorigin="anonymous">
     <link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
     <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons">
     <link rel="stylesgeet" href="https://rawgit.com/creativetimofficial/material-kit/master/assets/css/material-kit.css">
 </head>
 
 <body class="profile-page">
     <nav class="navbar navbar-color-on-scroll navbar-transparent    fixed-top  navbar-expand-lg "  color-on-scroll="100"  id="sectionsNav">
         <div class="container">
             <div class="navbar-translate">
                 <!-- <a class="navbar-brand" href="../index.html">Material Kit </a> -->
                 <button class="navbar-toggler" type="button" data-toggle="collapse" aria-expanded="false" aria-label="Toggle navigation">
                     <span class="navbar-toggler-icon"></span>
                     <span class="navbar-toggler-icon"></span>
                     <span class="navbar-toggler-icon"></span>
                 </button>
             </div>
         
             <div class="collapse navbar-collapse">
                 <ul class="navbar-nav ml-auto">
                     <li class="dropdown nav-item">
                       <!-- <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown" aria-expanded="false">
                           <i class="material-icons">apps</i> Components
                       </a> -->
                       <div class="dropdown-menu dropdown-with-icons">
                         <a href="../index.html" class="dropdown-item">
                             <i class="material-icons">layers</i> All Components
                         </a>
                         
                         <a href="http://demos.creative-tim.com/material-kit/docs/2.0/getting-started/introduction.html" class="dropdown-item">
                             <i class="material-icons">content_paste</i> Documentation
                         </a>
                       </div>
                     </li>
                       <li class="nav-item">
                           <a class="nav-link" href="javascript:void(0)">
                               <i class="material-icons">cloud_download</i> Download
                           </a>
                       </li>
                       <li class="nav-item">
                           <a class="nav-link"  target="_blank">
                           <!-- <a class="nav-link" href="https://twitter.com/CreativeTim" target="_blank"></a> -->
                               <i class="fa fa-twitter"></i>
                           </a>
                       </li>
                       <li class="nav-item">
                           <!-- <a class="nav-link" href="https://www.facebook.com/CreativeTim" target="_blank"> -->
                           <a class="nav-link"  target="_blank">

                               <i class="fa fa-facebook-square"></i>
                           </a>
                       </li>
                       <li class="nav-item">
                           <!-- <a class="nav-link"  href="https://www.instagram.com/CreativeTimOfficial" target="_blank"> -->
                           <a class="nav-link" target="_blank">

                               <i class="fa fa-instagram"></i>
                           </a>
                       </li>
                 </ul>
             </div>
         </div>
     </nav>
     
     <div class="page-header header-filter" data-parallax="true" ></div>
     <div class="main main-raised">
         <div class="profile-content">
             <div class="container">
                 <div class="row">
                     <div class="col-md-6 ml-auto mr-auto">
                        <div class="profile">
                             <div class="avatar">
                                 <img src = {{object.avatar.url}}>
                             </div>
                             <div class="name">
                                 <h3 class="title">{{object.first_name}} {{object.last_name}}</h3>
                                 <h6>{{object.email}}</h6>
                                 <a  class="btn btn-just-icon btn-link btn-dribbble"><i class="fa fa-dribbble"></i></a>
                                 <a class="btn btn-just-icon btn-link btn-twitter"><i class="fa fa-twitter"></i></a>
                                 <a class="btn btn-just-icon btn-link btn-pinterest"><i class="fa fa-pinterest"></i></a>
                             </div>
                         </div>
                     </div>
                 </div>
                 <div class="description text-center">
                     <h5>{{object.description}} </h5>
                 </div>
                 <!-- <div class="row">
                     <div class="col-md-6 ml-auto mr-auto">
                         <div class="profile-tabs">
                           <ul class="nav nav-pills nav-pills-icons justify-content-center" role="tablist">
                             <li class="nav-item">
                                 <a class="nav-link active" href="#studio" role="tab" data-toggle="tab">
                                   <i class="material-icons">camera</i>
                                   Studio
                                 </a>
                             </li>
                             <li class="nav-item">
                                 <a class="nav-link" href="#works" role="tab" data-toggle="tab">
                                   <i class="material-icons">palette</i>
                                     Work
                                 </a>
                             </li>
                             <li class="nav-item">
                                 <a class="nav-link" href="#favorite" role="tab" data-toggle="tab">
                                   <i class="material-icons">favorite</i>
                                     Favorite
                                 </a>
                             </li>
                           </ul>
                         </div>
                 </div> -->
             </div>
             <br>
             <!-- <div class = "container "> -->
                <div class="align-items-center" id="framewrap">
                    <div class="row justify-content-center mb-4">
                      <div class="col-md-8 col-lg-6 text-center">
                        <img id ="loader1" src="{%static 'home/images/loading.gif' %}">
                      </div>
                    </div>
                    <iframe  id="iframe1" src={{object.link}} name="iframe_a" padding="20px" height="800px" width="100%" title="EquStatus Viberational Analysics Dashboard" scrolling="no"></iframe>
                </div>
            
                  <script>
                    document.getElementById('iframe1').style.display = "none";
                    window.onload = function(){
                       document.getElementById('loader1').style.display = "none";
                       document.getElementById('iframe1').style.display = "block";
                    }        
                    
                  </script>
            <!-- <iframe src="https://studygyaan.com/django/how-to-setup-django-applications-with-apache-and-mod-wsgi-on-ubuntu" name="iframe_a" padding="20px" height="800px" width="100%" title="EquStatus Viberational Analysics Dashboard" scrolling="no"></iframe> -->
            <br>
                
           <!-- <div class="tab-content tab-space">
             <div class="tab-pane active text-center gallery" id="studio">
                   <div class="row">
                       <div class="col-md-3 ml-auto">
                           <img src="https://images.unsplash.com/photo-1524498250077-390f9e378fc0?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=83079913579babb9d2c94a5941b2e69d&auto=format&fit=crop&w=751&q=80" class="rounded">
                           <img src="https://images.unsplash.com/photo-1528249227670-9ba48616014f?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=66b8e7db17b83084f16fdeadfc93b95b&auto=format&fit=crop&w=357&q=80" class="rounded">
                       </div>
                       <div class="col-md-3 mr-auto">
                           <img src="https://images.unsplash.com/photo-1521341057461-6eb5f40b07ab?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=72da2f550f8cbd0ec252ad6fb89c96b2&auto=format&fit=crop&w=334&q=80" class="rounded">
                           <img src="https://images.unsplash.com/photo-1506667527953-22eca67dd919?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=6326214b7ce18d74dde5e88db4a12dd5&auto=format&fit=crop&w=750&q=80" class="rounded">
                       </div>
                   </div>
               </div>
             <div class="tab-pane text-center gallery" id="works">
                   <div class="row">
                       <div class="col-md-3 ml-auto">
                       <img src="https://images.unsplash.com/photo-1524498250077-390f9e378fc0?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=83079913579babb9d2c94a5941b2e69d&auto=format&fit=crop&w=751&q=80" class="rounded">
                         <img src="https://images.unsplash.com/photo-1506667527953-22eca67dd919?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=6326214b7ce18d74dde5e88db4a12dd5&auto=format&fit=crop&w=750&q=80" class="rounded">
                         <img src="https://images.unsplash.com/photo-1505784045224-1247b2b29cf3?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=ec2bdc92a9687b6af5089b335691830e&auto=format&fit=crop&w=750&q=80" class="rounded">  					</div>
                       <div class="col-md-3 mr-auto">
                       <img src="https://images.unsplash.com/photo-1504346466600-714572c4b726?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=6754ded479383b7e3144de310fa88277&auto=format&fit=crop&w=750&q=80" class="rounded">
                       <img src="https://images.unsplash.com/photo-1494028698538-2cd52a400b17?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=83bf0e71786922a80c420c17b664a1f5&auto=format&fit=crop&w=334&q=80" class="rounded">
                       </div>
                   </div>
               </div>
             <div class="tab-pane text-center gallery" id="favorite">
                   <div class="row">
                       <div class="col-md-3 ml-auto">
                         <img src="https://images.unsplash.com/photo-1504346466600-714572c4b726?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=6754ded479383b7e3144de310fa88277&auto=format&fit=crop&w=750&q=80" class="rounded">
                       <img src="https://images.unsplash.com/photo-1494028698538-2cd52a400b17?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=83bf0e71786922a80c420c17b664a1f5&auto=format&fit=crop&w=334&q=80" class="rounded">
                       </div>
                       <div class="col-md-3 mr-auto">
                         <img src="https://images.unsplash.com/photo-1505784045224-1247b2b29cf3?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=ec2bdc92a9687b6af5089b335691830e&auto=format&fit=crop&w=750&q=80" class="rounded">  					
                         <img src="https://images.unsplash.com/photo-1524498250077-390f9e378fc0?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=83079913579babb9d2c94a5941b2e69d&auto=format&fit=crop&w=751&q=80" class="rounded">
                         <img src="https://images.unsplash.com/photo-1506667527953-22eca67dd919?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=6326214b7ce18d74dde5e88db4a12dd5&auto=format&fit=crop&w=750&q=80" class="rounded">
                       </div>
                   </div>
               </div>
           </div> -->
 
         
             </div>
         </div>
     </div>
     
     <!-- <footer class="footer text-center ">
         <p>Made with <a href="https://demos.creative-tim.com/material-kit/index.html" target="_blank">Material Kit</a> by Creative Tim</p>
     </footer> -->


     <script type="text/javascript" src="{% static 'home/main.js' %}"></script>
     <script src="https://unpkg.com/popper.js@1.12.6/dist/umd/popper.js" integrity="sha384-fA23ZRQ3G/J53mElWqVJEGJzU0sTs+SvzG8fXVWP+kJQ1lwFAOkcUOysnlKJC33U" crossorigin="anonymous"></script>
     <script src="https://unpkg.com/bootstrap-material-design@4.1.1/dist/js/bootstrap-material-design.js" integrity="sha384-CauSuKpEqAFajSpkdjv3z9t8E7RlpJ1UP0lKM/+NdtSarroVKu069AlsRPKkFBz9" crossorigin="anonymous"></script>
 
 </body>
 

DataHub/home/templates/home/login.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>DataHub</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet"  href="{% static 'home/style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
  <body>
    <div class="container backdisplay">

      <div class="container">
        <div class="jumbotron">
          <h1>Login here :</h1>
          <form method="post" action="{% url 'home:login' %}">
            {% csrf_token %}

            <label for="username">Username:</label>
            <input type="text" name="username" placeholder="Username">
            <label for="password">Password:</label>
            <input type="password" name="password" placeholder="Password">
    
            {% if request.GET.next %}
              <input type ='hidden' name ="next" value ="{{ request.GET.next }}">
            {% endif %}
    
            <input type="submit" name="" value="Login">
            <a href="/signup/">SignUp</a>
          </form>
      </div>
    </div>

    </div>
  </body>
</html>

DataHub/home/templates/home/myprofile.html
{% extends 'base.html' %}

{% block title %}
my profile
{% endblock title %}

{% block content %}
<!-- <!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>    <title>My Profile: {{profile}}</title>
</head>
<body> -->
    <!-- <h1>My Profile</h1>
    <hr>
    <img src={{profile.avatar.url}}>
    <br>
    {{profile.avatar.url}}
    <br>
    {{profile.avatar}}
    <hr>
    {{profile.first_name}}
    <br>
    {{profile.last_name}}
    <br>
    {{profile.description}}
    <br>
    {{profile.get_friend_no}}
    <br> -->

    <div class="ui segment">

        <h3>my profile: {{request.user}}</h3>
        <div class="ui grid">
            <div class='row'>
                <div class='six wide column'>
                    <img class="ui medium rounded image" src={{profile.avatar.url}}> 
                </div>
                <div class="ten wide column">
                    <table class="ui table">
                        <tbody>
                            <tr>
                                <td>username</td>
                                <td>{{profile.user}}</td>
                            </tr>
                            <tr>
                                <td>first name</td>
                                <td>{{profile.first_name}}</td>
                            </tr>
                            <tr>
                                <td>last name</td>
                                <td>{{profile.last_name}}</td>
                            </tr>
                            <tr>
                                <td>bio</td>
                                <td>{{profile.description}}</td>
                            </tr>
                            <!-- <tr>
                                <td>number of followers</td>
                                <td>{{profile.get_followers_no}}</td>
                            </tr> -->

       
                            <!-- <tr>
                                <td>number of likes given</td>
                                <td>{{profile.get_likes_given_no}}</td>
                            </tr> -->
                            <!-- <tr>
                                <td>number of likes received</td>
                                <td>{{profile.num_likes}}</td>
                            </tr>
                            <div class="content">
                                <form action ="" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name='account_id' value={{profile.id}}>
                                </form>
                                <button type ="submit" class ="ui primary button">Like</button>
                            </div>     -->
                            
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

<!-- </body> -->

DataHub/home/templates/home/signup.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>DataHub</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet"  href="{% static 'home/style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
  <body>
    <div class="container backdisplay">
        <div class="jumbotron backdisplay" >
            <h1>Sign Up</h1>
    <form enctype="multipart/form-data" method="POST">
              {% csrf_token %}
              {{ user_form.as_p }}
              {{ profile_form.as_p }}
              <input type="submit" name="" value="Register">
            </form>
            <a href="/login/">
              Login
            </a>
          
        </div>
      </div>
  </body>
</html>